Repository hmcts/pcq-consolidation-service, pull requests merged in 2021-11, with the labels that each got.

#88 PCQ-1114Functional Test
  compose/backend.yml
  src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceTestBase.java
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-88

#85 PCQ-1020Consolidation Service
  compose/backend.yml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-85

#89 Pcq 1120 dependency check
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-89

#90 Pcq 1114 fix functional tests again
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceTestBase.java
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-90

#91 PCQ-1141: Consolidation service dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-91
