Repository hmcts/pcq-consolidation-service, pull requests merged in 2021-08, with the labels that each got.

#78 PCQ-1003: Update to fix functional tests.
  src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceTestBase.java
  src/functionalTest/resources/JsonTestFiles/SecondSubmitAnswerWithDcn.json
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-78

#79 fix pcq-consolidation vulnerability
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-79

#80 springFrameworkUpgrade
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-80

#81 Sync Branches with master
  Jenkinsfile_CNP
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-81
