Repository hmcts/pcq-consolidation-service, pull requests merged in 2021-12, with the labels that each got.

#92 PCQ-1190Disable Consolidation
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-92

#93 PCQ-1190 log4j upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-93

#95 PCQ-1212 Enable Fortify Scan
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-95

#94 PCQ‐1134: Update pcq-consolidation-service to Gradle 7.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-94
