Repository hmcts/pcq-consolidation-service, pull requests merged in 2021-07, with the labels that each got.

#74 PCQ-874: Update to remove IdAM admin password from scripts.
  bin/env_variables_all.txt
  bin/idam-client-setup.sh
  bin/idam-role-assignable.sh
  bin/idam-role.sh
  compose/README.md
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-74

#75 PCQ-885: UpdatedPcqCommonsLocation
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-75

#76 fix for CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-76

#77 PCQ-880: Updated to add fortify pipeline
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-77
