Repository hmcts/pcq-consolidation-service, pull requests merged in 2022-07, with the labels that each got.

#121 PCQ-914 Dependency check fixed
  charts/pcq-consolidation-service/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-121

#122 Pcq 941 fix pipeline issues
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  azure-pipelines-scheduled.yml
  azure-pipelines.yml
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-122

#123 PCQ-896 Upgrade dependabot
  .dependabot/dependabot.yml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-123

#125 Pcq 896
  .github/dependabot.yml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-125

#136 Pcq 896
  .github/renovate.json
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-136

#147 PCQ-1456dependency check fix
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-147
