Repository hmcts/pcq-consolidation-service, pull requests merged in 2022-02, with the labels that each got.

#97 PCQ-1236 HMCTS library upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-97

#98 PCQ-1338 Dependency check fixed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-98

#99 PCQ-986: Spring Security dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-99

#100 Pcq 1339
  charts/pcq-consolidation-service/Chart.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-100
