Repository hmcts/pcq-consolidation-service, pull requests merged in 2022-05, with the labels that each got.

#110 PCQ-1421-remove-redundant-vulnerability-suppressions
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-110

#111 PCQ-1421-remove-redundant-vulnerability-suppressions-2
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-111

#113 PCQ-1333 Spring upgrade
  Jenkinsfile_nightly
  build.gradle
  security.sh
  src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/config/SwaggerConfiguration.java
  src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/impl/PcqBackendServiceImplTest.java
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-113

#115 Pcq 1333 consolidation
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-115

#117 PCQ-699 Dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-117
