Repository hmcts/pcq-consolidation-service, pull requests merged in 2022-04, with the labels that each got.

#106 PCQ-966-dependency-check-spring-beans
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-106

#107 PCQ-1452: Suppress spring-plugin vulnerabilities
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-107

#108 PCQ-1424-Dependency-check-spring-plugin
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-108

#109 PCQ-1423-dependency-check-spring-5.3.18
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-109
