Repository hmcts/pcq-consolidation-service, pull requests merged in 2022-11, with the labels that each got.

#180 PCQ-1596 dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-180

#181 PCQ-1593 Add SonarQube badges and Overview section
  README.md
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-181

#182 PCQ-1595 Cleanup helm release on success
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-182

#183 PCQ-1600upgrading libraries
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-183

#194 PCQ-1600Upgrading more libraries
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-consolidation-service-pr-194
